Test/test
DittoAdrian/chill-backend pull request #1
Opened 2024-12-07 04:54 UTC by DittoAdrian

Tolong di Cek Mass, saya ngelakuin perubahan 
- struktur database(local storage)
- .env
- .gitignore *saya gatau kenapa .env masih masuk ke github padahala saya sudah buat gitignore
- merapihkan CRUD database.js *yang ini diabaika aja

- cek kelengkapan data function loginUser 
- function mengirim token baru di dalam function loginUser

2024-12-07 05:28 UTC, ardy-yusuf-wibawa commented on .env
> +MYSQL_HOST=127.0.0.1
best practicenya, jangan pernah isi value untuk .env lalu gunakan nama `.env example` dan tambahkan juga .env pada .gitignore supaya tidak terbawa pada saat push ke production

2024-12-07 05:28 UTC, ardy-yusuf-wibawa commented on .gitignore
> +.env
jika kalau .env masih ada didalam repo, maka perlu langsung mendelete di workspac, hal ini terjadi karena init pertama tidak menggunakan .gitignore

tambahkan juga node_modules tidak perlu di masukan kedalam repo, karena node_modules bisa didapatkan dari package.json

2024-12-07 05:28 UTC, ardy-yusuf-wibawa commented on database.js
> -import mysql from 'mysql2';
project-root/
|-- src/
|   |-- controllers/        # Handles HTTP requests and responses
|   |   |-- userController.js  # Example controller for user-related actions
|   |
|   |-- services/           # Contains business logic
|   |   |-- userService.js     # Example service for user-related logic
|   |
|   |-- repositories/       # Handles data access logic
|   |   |-- userRepository.js  # Example repository for user-related data access (database query)
|   |
|   |-- models/             # Database models or schemas
|   |
|   |-- routes/             # Route definitions and mappings to controllers
|   |-- middlewares/        # Middleware functions
|   |-- utils/              # Utility functions and helpers
|   |    |-- database.js # For auth to database only (no query related)
|
|-- config/                 # Application configuration files
|-- tests/                  # Test cases for all layers
|-- package.json            # Node.js project metadata
|-- README.md               # Project overview and instructions

ini best practice structure folder design umumnya, secara functionality code yang diberikan pada database.js bisa digunakan tetapi secara umum kurang baik karena akan sangat repot untuk mengurus atau mengembangkan querynya kedepannya

2024-12-07 05:30 UTC, ardy-yusuf-wibawa commented on database.js
> -import dotenv from 'dotenv';
jika sudah bisa membuat dengan folder dan structure yang baik, bisa pertimbangkan untuk menggunakan library seperti prisma atau sequalize untuk bisa lebih related dengan kebutuhan industri kedepannya

2024-12-09 13:05 UTC, DittoAdrian commented
Mas Ardy, ini Struktur folder yang baru. saya pecah dari 2 file sebelum nya manjadi 7 file di dalam folder src sesuai strandarisasi struktur folder api

2024-12-09 17:32 UTC, ardy-yusuf-wibawa requested changes

2024-12-09 17:32 UTC, ardy-yusuf-wibawa commented on src/controllers/controllerUser.js
> +        const users = await getUsersS();
gunakan name convention yang baik misal jika ingin menggunakan function pada service, maka penamaanya menjad `getUsersService` ini berlaku untuk semua yang berhubungan dengan service, menggunakan camelCase dan berakhiran service

2024-12-09 17:32 UTC, ardy-yusuf-wibawa commented on src/index.js
> +app.use(router);
index ini berada di luar controller atau di hirarki paling atas, sejajar dengan `src`, kenapa demikian karena 
```
app.use(router)
```

2024-12-09 17:32 UTC, ardy-yusuf-wibawa commented on src/repositories/userRepository.js
> +import bcrypt from "bcrypt";
nice ini udah baik implementnya

2024-12-09 17:32 UTC, ardy-yusuf-wibawa commented on src/utils/database.js
> +export { pool };
overall sudah baik semuanya secara folder structure, tinggal implement middleware-nya saja yang kurang

2024-12-09 17:32 UTC, ardy-yusuf-wibawa commented on src/services/service.js
> +export const getUsersS = async () => {
gunakan naming convention yang baik dan benar maka ini akan lebih baik dan lebih mudah dimengerti

2024-12-09 17:32 UTC, ardy-yusuf-wibawa commented on src/services/service.js
> +import bcrypt from "bcrypt";
jika semua logika business untuk user disini semua, maka baiknya menjad `userService.js`

2024-12-09 17:32 UTC, ardy-yusuf-wibawa commented on src/utils/database.js
> +export { pool };
bagaimana lebih enak dan lebih mudah dimengerti bukan jika dipisah2 seperti ini

2024-12-09 17:33 UTC, ardy-yusuf-wibawa commented
ini di merge dulu ke master, setelah itu tambahkan middleware di brach terbaru, supaya tidak terlalu banyak commit dan comment dalam sebuah pull request

2024-12-09 19:29 UTC, DittoAdrian commented on src/utils/database.js
> +export { pool };
haha iya mas, jadi lebih ganpang buat ngedevelop nya

2024-12-09 19:29 UTC, merged

2024-12-09 19:41 UTC, DittoAdrian commented on src/services/service.js
> +export const getUsersS = async () => {
okk mas diganti

2024-12-09 19:45 UTC, DittoAdrian commented on src/services/service.js
> +export const getUsersS = async () => {
karna saya baru gunain struktur folder seperti ini dan awalnya kurang paham tiap folder kegunaannya buat apa. jadi tiap fungsi nya saya coba namain yang gampang dulu